### PR TITLE
Adding a CommonJS export

### PR DESCRIPTION
**Pull request by shahkashani**
👋 

First of all, thank you so much for a wonderful library, it's made life so much easier for us.

I ran into some issues while unit testing a component that uses AudioMotionAnalyzer, and this diff is the least intrusive fix I was able to find. It's not 100% ideal, because it expects downstream consumers transpile the library code, but on the upside it does offer _a_ solution and it doesn't make too many changes to the way this library is managed.

### What is the issue?

I made a repository to illustrate the problem and there are reproduction steps there: https://github.com/shahkashani/audiomotion-tester

Essentially, our TS/TSX files are often transpiled into CommonJS, but since AudioMotionAnalyzer doesn't offer a CJS export, jest (and eventually babel, when it comes to time to preparing the code for the browser) is unable to find it. 

Screenshot 2024-03-21 at 11 17 27

This PR doesn't offer a compiled CommonJS bundle, but it does at least allow a path into creating one. Without this line in `package.json`, there is no way of making this library work for us as far as I can tell.

If there are alternate solutions or any concerns, please let me know. 

Again, thank you so much and keep up the great work!

### CODE REVIEW

**Comment by hvianna** [comment]
Hello! Thanks for adding more info to your [issue](https://github.com/hvianna/audioMotion-analyzer/issues/71) and for proposing an initial solution.

I would prefer exporting to a UMD-compatible module, for broader compatibility, so I've been looking into using Babel and it's [transform-modules-umd](https://www.npmjs.com/package/@babel/plugin-transform-modules-umd) but the output is not perfect. You need to add `.default` to the require statement (and to the global variable for browser usage), which looks really bad. I then found about the [add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports) plugin, but it [doesn't seem to work](https://github.com/59naga/babel-plugin-add-module-exports/issues/73) with the latest versions of Babel preset-env.

I have no experience in generating these old-style modules, so I'm kinda lost here. Would you have any suggestion on how to properly export to UMD format?

**Comment by shahkashani** [comment]
@hvianna That is totally fair! I took a stab at it. It uses `parcel` to create the cjs asset, the idea is to do this automatically every time before the library gets pushed to `npm` (though I haven't tested this particular part of it). I didn't add the `dist` folder to `.gitignore`, but maybe it should be there?

Anyway, overall it seems to do the trick for this particular jest problem! Testing steps below.

In this repo:

1. Grab the latest changes committed into this branch
1. Run `npm i` to pull down Parcel
1. To make sure the script works: `npm run build`
1. `npm link`

In `https://github.com/shahkashani/audiomotion-tester`:

1. `git pull origin main`
1. `npm link audiomotion-analyzer`
1. `npm run test` 

Screenshot 2024-03-23 at 10 21 43

I ran the `npm start` script for `audioMotion-analyzer` and made sure all the examples still work as-is, but I absolutely may have missed something. For instance, I didn't test if the `commonjs` version works in a browser. So, if anything seems off, please let me know!

**Comment by shahkashani** [comment]
Anything I can do to help out with this one? ☺️

**Comment by hvianna** [comment]
@shahkashani I'll look into it this weekend!

**Comment by hvianna** [comment]
So the module exported by Parcel also needs an extra `.default` to work, like so:

```
const AudioMotionAnalyzer = require('audiomotion-analyzer').default;
```

Not optimal, but it seems we won't get anything better with the current state of modules and tools.

**Comment by shahkashani** [comment]
Ah, right! I wonder if exporting a named library (and the existing default for es6) would allow a nicer state of things for cjs? Something like:

```javaScript
export const AudioMotionAnalyzer;
export default AudioMotionAnalyzer;
```

**Comment by hvianna** [comment]
I was looking at the code again and realized that the generated `audioMotion-analyzer-cjs.js` is still an ES module and not CJS format. It's essentially the original source code with only some local names changed by Parcel, and still using the ES6 native `export` statement, instead of CJS `exports` object.

So if that code solved the issue for you, maybe all we need is the `"require": "./src/audioMotion-analyzer.js"` line in package.json after all? 🤔

I also added a named export to the original module, so `const { AudioMotionAnalyzer } = require('audiomotion-analyzer');` now works, at least with Webpack.

Can you please install the new version with `npm i audiomotion-analyzer@beta` and see if it works for you now? The updated code is also available in the `develop` branch if you prefer.

**Comment by shahkashani** [comment]
Thanks so much for taking another look at this!

Out of the box ([using this setup](https://github.com/shahkashani/audiomotion-tester)), it doesn't seem to work:

Screenshot 2024-04-29 at 18 13 06

But in my Jest config, if I tell Jest to pass things Babel, like so:

```diff --git a/jest.config.js b/jest.config.js
index 0e846ae..a116230 100644
--- a/jest.config.js
+++ b/jest.config.js
@@ -3,4 +3,5 @@ module.exports = {
   preset: 'ts-jest',
   testEnvironment: 'jsdom',
   transform: { '^.+\\.[tj]s$': 'ts-jest' },
+  transformIgnorePatterns: ['node_modules/(?!audiomotion-analyzer)'],
 };

Then it does work. So I think that's least an improvement, because it provides at least a path.

I do wonder if what Parcel is doing is enough to make things work successfully for `cjs`, since I was able to get it to work [here](https://github.com/hvianna/audioMotion-analyzer/pull/72#issuecomment-2016424168) without passing things through Babel.

**Comment by hvianna** [comment]
I see you're using `import AudioMotionAnalyzer from 'audiomotion-analyzer';` in your test setup.

What if you change that to `const { AudioMotionAnalyzer } = require('audiomotion-analyzer');`

**Comment by shahkashani** [comment]
Same problem :( 

Screenshot 2024-04-29 at 20 21 59

**Comment by hvianna** [comment]
Have you tried enabling ESM support on Jest? https://jestjs.io/docs/ecmascript-modules

**Comment by shahkashani** [comment]
Unfortunately, that seems to make everything act very strangely.

Screenshot 2024-04-30 at 09 01 58

Screenshot 2024-04-30 at 09 04 22

Maybe it's okay though to start with the changes you have in the beta, at least it provides a path for Babel compilation for those who might need it ☺️

**Comment by hvianna** [comment]
I just pushed 4.5.0-beta.1 to npm, can you give it a try?
This is my attempt at generating an UMD module with Babel. Source code is in the `umd` branch.

**Comment by shahkashani** [comment]
You are amazing. This works like an absolute charm! 🎉 
 
Screenshot 2024-05-02 at 15 22 01

I really appreciate your help on this, and I hope this change doesn't make your workflow more painful!

**Comment by hvianna** [comment]
Awesome, glad it worked!

@Staijn1 @cprussin @alex-greff If you guys have the chance would you be so kind as to try out the new beta and confirm that it still works in your current environment? I'd like to make sure I didn't break anything for anyone else 😅

**Comment by Staijn1** [comment]
I've updated my Angular project to use the beta and I see no immediate errors.
The deployment of my project is currently running and I will report back if I see any anomalies whilst using Audiomotion, but as of right now everything looks good!

**Comment by hvianna** [comment]
> I've updated my Angular project to use the beta and I see no immediate errors. The deployment of my project is currently running and I will report back if I see any anomalies whilst using Audiomotion, but as of right now everything looks good!

Much appreciated! 🙏

**Comment by Staijn1** [comment]
I tested it today and did not run into any problems at runtime either. Looks good to me!

**Comment by hvianna** [comment]
> I tested it today and did not run into any problems at runtime either. Looks good to me!

Thanks again!

Stable v4.5.0 should be out next weekend, maybe sooner if I get the chance.

**Comment by shahkashani** [comment]
Thank you so much again!!

**Pull request closed without merging**
